# Generated by Django 3.2 on 2021-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('SKU', models.CharField(max_length=75)),
                ('brand_Name', models.CharField(choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('MI', 'Xiaomi Mi'), ('OPPO', 'Oppo'), ('REALME', 'Realme'), ('VIVO', 'Vivo'), ('ONEPLUS', 'One Plus')], default='APPLE', max_length=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('in_Stock', models.BooleanField(default=True)),
            ],
        ),
    ]
